config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'home/about' => 'homes#about', as: 'homes_about'
  devise_for :users
  resources :books
  resources :users, only: [:index,:show,:edit,:update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to:user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  belongs_to :user
  attachment :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attr_accessor :remember_token
  has_many :books
  validates :name, presence: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
  
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

def after_sign_out_path_for(resource)
    root_path
end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 before_action :authenticate_user!
 before_action :correct_user, only: [:edit, :up]

  def create

    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    flash[:notice] = "You have created book successfully.."
    redirect_to book_path(@book)
    else
    @books = Book.all
    render 'index'
    end
  end
  def index
      @books = Book.all
      @book = Book.new
      @user = current_user
  end

  def show
      @book = Book.find(params[:id])
      @user = current_user
  end

  def edit
      @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:notice] = "Book was successfully updated."
    redirect_to book_path(@book)
    else
    @books = Book.all
    render 'index'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "Book was successfully destroyed."
    redirect_to books_path(@book)
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    if @book.user != current_user
    redirect_to books_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show,:edit,:index,:update]
  before_action :correct_user, only: [:edit, :update]
  # def login
  #   @user = User.find_by(email: params[:email], password: params[:password])
  #   if @user
  #     flash[:notice] = "Welcome! You have signed up successfully."
  #     redirect_to user_path
  #   else
  #     render new_user_session_path
  #   end
  # end

  def index
    @users = User.all
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  # def create
  #   @user = User.new(user_params)
  #   @user.save
  #   flash[:notice] = "You have created book successfully."
  #   redirect_to root_path
  # end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:notice] = "User was successfully updated."
    redirect_to user_path(@user)
    else
    render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def correct_user
    user = User.find(params[:id])
    if user != current_user
    redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_with model:@book, local:true do |f| %>
  <h4>title</h4>
  <%= f.text_field :title %>
  <h4>body</h4>
  <%= f.text_area :body %>
  <h4> </h4>
  <%= f.submit 'Update Book' %>
<% end %>
<%= link_to "Show", book_path(@book.id) %>
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<div class="body">
    <div class="container">
        <div class="row">
            <div class="col-xs-3">
              <%= render 'layouts/error_messages', book: @book %>
              <%= render 'layouts/userinfo', book: @book, user: current_user %>
            </div>

            <div class="col-xs-9">
              <h4>Books</h4>

                <table class="table table-hover table-inverse">
                      <th></th>
                      <th>Title</th>
                      <th>Opinion</th>
                    <% @books.each do |book| %>
                      <tr>
                        <td><%=link_to  user_path(book.user.id) do %>
          								<%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, format: 'jpeg', class: " profile-img", fallback: "no_image.jpg", size:'50x50' %>
          							<%end%>
          							</td>
                        <td><span><%= link_to book.title, book_path(book.id) %></span></td>
                        <td><span><%=link_to book.body, book_path(book.id) %></span></td>
                      </tr>
                     <% end %>
                </table>
            </div>
        </div>
    </div>
  </div>

app/views/books/show.html.erb
<div class="body">
    <div class="container">
      <%=flash[:notice] %>
        <div class="row">
            <div class="col-xs-3">
              <%= render 'layouts/userinfo', book: Book.new, user: @book.user %>
            </div>

            <div class="col-xs-9">
              <h4>Book detail</h4>
              <table class="table table-hover table-inverse">
                <thead>
                  <tr>
                    <%=link_to  user_path(@book.user.id) do %>
      								<%= attachment_image_tag @book.user, :profile_image, :fill, 50, 50, format: 'jpeg', class: " profile-img", fallback: "no_image.jpg", size:'50x50' %>
      								<%= @book.user.name %>
      							<%end%>
                    <th>users</th>
                    <%= @book.title %>
                    <%= @book.body %>
                    <thcolspan="3"></thcolspan>
                    </th>
                    <% if @book.user==current_user %>
                    <td>
                    <%= link_to "Edit", edit_book_path(@book.id) %>
                    </td>
                    <td>
                    <%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？"%>
                    </td>
                    <%end%>

                  </tr>
                </thead>
              </table>
            </div>
        </div>
    </div>
  </div>

app/views/homes/about.html.erb
<h1>Welcome to
 <span class="glyphicon glyphicon-book"></span>
 Bookers!</h1>

app/views/homes/top.html.erb
  <body>
    <div class="body">
      <div class="container">
        <div class="row"
         <div class="top-message col-md-offset-3 col-md-6">
           <h1>
            welcomme to
            <strong>Bookers</strong>
            !!
           </h1>

           <p>In
             <strong>bookers</strong>
            ,</p>

           <p>you can share and exchange your opinions , inpressions , and emotions</p>

           <p>about various books!</p>

           <div>
            <%= link_to "Log in", new_user_session_path %>
           </div>
           <div>
            <%=link_to "Sign Up", new_user_registration_path %>
           </div>
           <% if flash[:notice] %>
            <div class="flash">
              <%= flash[:notice] %>
            </div>
          <% end %>
         </div>
        </div>
      </div>
    </div>

app/views/layouts/_error_messages.html.erb
<% if book.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <p>error</p>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_userinfo.html.erb
<h1>User info</h1>
  <table class="table">
    <tbody>
       <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
      <h4>name     <%= user.name %> </h4>
      <h4>introduction <%= user.introduction %></h4>
    </tbody>
 </table>
 <%= link_to '', edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
<h1>New book</h1>
 <%= form_with model:book, local:true do |f| %>

<h4>Title</h4>
  <%= f.text_field :title, class:"form-control" %>

<h4>Opinion</h4>
  <%= f.text_area :body, class:"form-control" %></br>

  <%= f.submit 'Create Book', class: "btn btn-default btn-block" %>
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!DOCTYPE html>
    <title>Bookers</title>
     <%= csrf_meta_tags %>
     <%= csp_meta_tag %>

     <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,600,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>
  </head>

  <body>


      <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <p class="navbar-brand" >Bookers</p>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%=link_to ' Home', user_path(current_user.id), class: "glyphicon glyphicon-home" %></li>
            <li><%=link_to ' Users', users_path,class: "glyphicon glyphicon-user" %></li>
            <li><%=link_to ' Books', books_path,class: "glyphicon glyphicon-book" %></li>
            <li><%=link_to ' logout', destroy_user_session_path, method: :delete,class: "glyphicon glyphicon-log-out" %></li>
          <% else %>
            <li><%=link_to ' Home', '/', class: "glyphicon glyphicon-home"%></li>
            <li><%=link_to ' About', '/home/about',class: "glyphicon glyphicon-link" %></li>
            <li><%=link_to ' sign up', new_user_registration_path,class: "glyphicon glyphicon-edit" %></li>
            <li><%=link_to ' login', new_user_session_path,class: "glyphicon glyphicon-log-in" %></li>
          <% end %>
        </ul>
      </div>
    </nav>




    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/edit.html.erb
<h1>User info</h1>
<%= form_for @user do |form| %>
	<% if @user.errors.any? %>
	  <div id="error_explanation">
	    <h2><%= @user.errors.count %>error prohibited this obj from being saved:</h2>
	    <ul>
	    <% @user.errors.full_messages.each do |message| %>
	      <li><%= message %></li>
	    <% end %>
	    </ul>
	  </div>
	<% end %>܀
	
 <h4>Name<h4>
  <%= form.text_field :name %>
 <h4>Image</h4>
                  <%= form.attachment_field :profile_image %>
                  <%= attachment_image_tag @user, :profile_image %>
 <h4>Introduction</h4>
 <%= form.text_area :introduction %>
 <%= form.submit 'Update User' %>
<% end %>

app/views/users/index.html.erb
<div class="body">
    <div class="container">
        <div class="row">
            <div class="col-xs-3">
              <%= render 'layouts/userinfo', book: Book.new, user: current_user %>
            </div>

            <div class="col-xs-9">
              <h4>Users</h4>
              <table class="table table-hover table-inverse">
                <thead>
                  <tr>
                    <th>Image</th>
                    <th>Name</th>
                    <thcolspan="3"></thcolspan></th>
                  </tr>
                </thead>
                <tbody>
                  <% @users.each do |user| %>
                    <tr>
                      <td>
                      <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %></td>
                      <td><%= user.name %></td>
                       <td>
                     <%= link_to "Show", user_path(user.id) %>
                    </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
        </div>
    </div>
  </div>

app/views/users/show.html.erb
<div class="body">
    <div class="container">
        <div class="row">
            <div class="col-xs-3">
              <%=flash[:notice] %>
              <%= render 'layouts/userinfo', book: Book.new, user: @user %>
            </div>

            <div class="col-xs-9">
              <h4>Books</h4>

              <table class="table table-hover table-inverse">
                <thead>
                  <tr>
                    <th></th>
                    <th>Title</th>
                    <th>Opinion</th>
                    <th colspan="3"></th>
                  </tr>
                </thead>
                <tbody>
                  <% @books.each do |book| %>
                    <tr>
                      <td>
                        <%=link_to  user_path(book.user.id) do %>
          								<%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, format: 'jpeg', class: " profile-img", fallback: "no_image.jpg", size:'50x50' %>

          							<%end%>
                      </td>
                      <td><%= link_to  book.title , book_path(book)%></td>
                      <td><%= book.body %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
        </div>
    </div>
  </div>